### ISSUE TITLE
Error on raven-reader

### ISSUE THREAD

**Issue by santiago-a-vidal** [dorellang/hunter#20]
https://github.com/mrgodhani/raven-reader is loaded but it has several nodes without connexion. For example src/renderer/config.example.js exports a variable that it is imported by cacheArticle.js and article.js. However, this relationship is not shown by Hunter

**Comment by dorellang** [comment]
For this project esprima doesn't have any parsing errors. Regarding the src/rendered/config.example.js, the link it's not shown because the code isn't actually importing that file, but rather config.example.js is like a template that the user has to copy to config.js and fill the values by himself. The other things that aren't connected seem to be the result of webpack weird stuff and electron; which I don't know if I could fix right now :S

**Comment by tinchodias** [comment]
I revisited this issue to understand more.
I understand as Diego that the config.example.js is a template that should be renamed to config.js. The travis configuration has this line: `cd  src/renderer && cp config.example.js config.js`. After doing it, the nodes mentioned by Santiago are connected (screen capture).
<img width="1240" alt="Screen Shot 2020-04-06 at 17 01 21" src="https://user-images.githubusercontent.com/3044265/78605071-e4bf7900-7828-11ea-9377-087518663594.png">
